import type { CatalogMember } from './member-catalog'

/** 妖族（万妖谷）人物名录（结构对齐青云宗） */
export const YAOZU_MEMBERS: CatalogMember[] = [
  {
    id: 'yz-1',
    name: '万妖王',
    title: '万妖谷主',
    realm: '化神后期',
    power: 255000,
    avatar: '万',
    tone: 'gold',
    group: '宗主',
    personality: '霸道、威严',
    specialty: '血脉、统御',
    note: '万妖归心，号令山林',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-2',
    name: '青丘狐帝',
    title: '副谷主',
    realm: '化神中期',
    power: 225000,
    avatar: '青',
    tone: 'gold',
    group: '宗主',
    personality: '狡黠、聪慧',
    specialty: '幻术、化形',
    note: '九尾未显，已足以惑人',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-3',
    name: '玄龟长老',
    title: '大长老',
    realm: '元婴后期',
    power: 140000,
    avatar: '玄',
    tone: 'mp',
    group: '长老',
    personality: '沉稳、古板',
    specialty: '炼丹、龟息',
    note: '丹阁以灵草与妖丹并重',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-4',
    name: '蝶母',
    title: '二长老',
    realm: '元婴中期',
    power: 122000,
    avatar: '蝶',
    tone: 'mp',
    group: '长老',
    personality: '温柔、聪慧',
    specialty: '灵药、医术',
    note: '掌握一处隐秘药谷',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-5',
    name: '金犀匠',
    title: '三长老',
    realm: '元婴后期',
    power: 138000,
    avatar: '金',
    tone: 'mp',
    group: '长老',
    personality: '豪爽、直率',
    specialty: '炼器、骨甲',
    note: '器阁多用妖骨妖角',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-6',
    name: '蛛网尊者',
    title: '四长老',
    realm: '元婴中期',
    power: 120000,
    avatar: '蛛',
    tone: 'mp',
    group: '长老',
    personality: '神秘、寡言',
    specialty: '阵法、蛛网',
    note: '谷中大阵丝丝相连',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-7',
    name: '醉猿',
    title: '五长老',
    realm: '元婴初期',
    power: 105000,
    avatar: '醉',
    tone: 'mp',
    group: '长老',
    personality: '懒散、爱喝酒',
    specialty: '占卜、兽语',
    note: '醉后能听懂百兽心声',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-8',
    name: '白虎判',
    title: '执法长老',
    realm: '元婴初期',
    power: 108000,
    avatar: '白',
    tone: 'mp',
    group: '长老',
    personality: '铁面无私',
    specialty: '审讯、追踪',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-9',
    name: '狼牙使',
    title: '执法堂堂主',
    realm: '金丹后期',
    power: 84000,
    avatar: '狼',
    tone: 'hp',
    group: '执事',
    personality: '冷酷、公正',
    specialty: '执法、近战',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-10',
    name: '仓鼠管事',
    title: '杂务执事',
    realm: '金丹初期',
    power: 61500,
    avatar: '仓',
    tone: 'jade',
    group: '执事',
    personality: '勤恳、琐碎',
    specialty: '庶务、账册',
    note: '经手外门杂役调配',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-11',
    name: '烈焰狮子',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 62000,
    avatar: '烈',
    tone: 'gold',
    group: '亲传弟子',
    personality: '清傲、好胜',
    specialty: '火系血脉',
    note: '谷主亲传，锋芒初露',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-12',
    name: '雪狐',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 35500,
    avatar: '雪',
    tone: 'gold',
    group: '亲传弟子',
    personality: '温婉、聪慧',
    specialty: '幻术、冰系',
    note: '副谷主座下亲传',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-13',
    name: '黑豹',
    title: '执法弟子',
    realm: '筑基后期',
    power: 32500,
    avatar: '黑',
    tone: 'hp',
    group: '内门弟子',
    personality: '暴躁',
    specialty: '近战',
    note: '',
    attitude: '容易与玩家冲突',
    sectId: 'yaozu'
  },
  {
    id: 'yz-14',
    name: '青雀',
    title: '执法弟子',
    realm: '筑基中期',
    power: 28200,
    avatar: '青',
    tone: 'hp',
    group: '内门弟子',
    personality: '认真',
    specialty: '调查、追踪',
    note: '',
    attitude: '对玩家较友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-15',
    name: '岩龟',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24000,
    avatar: '岩',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉稳、寡言',
    specialty: '土系防御',
    note: '常年镇守万妖谷后山',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-16',
    name: '小狸',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6900,
    avatar: '狸',
    tone: 'jade',
    group: '外门弟子',
    personality: '活泼、热心',
    specialty: '跑腿打听',
    note: '消息灵通',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-17',
    name: '青禾兔',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '青',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实、勤勉',
    specialty: '药园劳作',
    note: '一心想入内门',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-18',
    name: '阿牛',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5100,
    avatar: '阿',
    tone: 'jade',
    group: '杂役弟子',
    personality: '憨厚',
    specialty: '砍柴挑水',
    note: '谷中杂役数年',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-19',
    name: '小翠雀',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5400,
    avatar: '翠',
    tone: 'jade',
    group: '杂役弟子',
    personality: '机灵、嘴碎',
    specialty: '洒扫、传话',
    note: '常在膳堂附近转悠',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-101',
    name: '陈清尘',
    title: '丹阁执事',
    realm: '金丹中期',
    power: 72000,
    avatar: '陈',
    tone: 'jade',
    group: '执事',
    personality: '圆滑',
    specialty: '妖丹调配、丹房巡察',
    note: '协理大长老药事',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-102',
    name: '胡明远',
    title: '器阁执事',
    realm: '金丹初期',
    power: 63000,
    avatar: '胡',
    tone: 'jade',
    group: '执事',
    personality: '懒散',
    specialty: '骨料清点、炼器后勤',
    note: '常与三长老往来',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-103',
    name: '梁芙蕖',
    title: '外门执事',
    realm: '金丹初期',
    power: 60000,
    avatar: '梁',
    tone: 'jade',
    group: '执事',
    personality: '认真',
    specialty: '外门考勤、弟子调度',
    note: '外门弟子多惧其簿册',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-104',
    name: '朱明远',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 58000,
    avatar: '朱',
    tone: 'gold',
    group: '亲传弟子',
    personality: '认真',
    specialty: '炼丹入门',
    note: '大长老座下亲传',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-105',
    name: '宋芙蕖',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 36000,
    avatar: '宋',
    tone: 'gold',
    group: '亲传弟子',
    personality: '随和',
    specialty: '医理、灵药',
    note: '二长老座下亲传',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-106',
    name: '萧若虚',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 34000,
    avatar: '萧',
    tone: 'gold',
    group: '亲传弟子',
    personality: '热心',
    specialty: '骨甲锤锻',
    note: '三长老座下亲传',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-107',
    name: '曾正阳',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 32000,
    avatar: '曾',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷酷',
    specialty: '蛛阵推演',
    note: '四长老座下亲传',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-108',
    name: '丁剑影',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 33000,
    avatar: '丁',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷艳',
    specialty: '律法、审讯',
    note: '执法长老座下亲传',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-109',
    name: '董知微',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31000,
    avatar: '董',
    tone: 'jade',
    group: '内门弟子',
    personality: '冷静',
    specialty: '血脉勤修',
    note: '有望冲击亲传考核',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-110',
    name: '沈有恒',
    title: '内门弟子',
    realm: '筑基后期',
    power: 30000,
    avatar: '沈',
    tone: 'jade',
    group: '内门弟子',
    personality: '狂傲',
    specialty: '兽符抄写',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-111',
    name: '贾望川',
    title: '内门弟子',
    realm: '筑基中期',
    power: 27000,
    avatar: '贾',
    tone: 'jade',
    group: '内门弟子',
    personality: '嗜杀',
    specialty: '护谷巡逻',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-112',
    name: '杜鸾音',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26500,
    avatar: '杜',
    tone: 'jade',
    group: '内门弟子',
    personality: '娇蛮',
    specialty: '藏经整理',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-113',
    name: '范素心',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26000,
    avatar: '范',
    tone: 'jade',
    group: '内门弟子',
    personality: '阴柔',
    specialty: '丹房助手',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-114',
    name: '金听雨',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24500,
    avatar: '金',
    tone: 'jade',
    group: '内门弟子',
    personality: '残忍',
    specialty: '器房学徒',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-115',
    name: '邱疏影',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24000,
    avatar: '邱',
    tone: 'jade',
    group: '内门弟子',
    personality: '机灵',
    specialty: '阵基维护',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-116',
    name: '龙怀橘',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23500,
    avatar: '龙',
    tone: 'jade',
    group: '内门弟子',
    personality: '文静',
    specialty: '灵田督耕',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-117',
    name: '易厚德',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25500,
    avatar: '易',
    tone: 'jade',
    group: '内门弟子',
    personality: '谨慎',
    specialty: '外勤传讯',
    note: '有望冲击亲传考核',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-118',
    name: '聂悟真',
    title: '内门弟子',
    realm: '筑基后期',
    power: 30500,
    avatar: '聂',
    tone: 'jade',
    group: '内门弟子',
    personality: '嘴碎',
    specialty: '内务协理',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-119',
    name: '刘铸剑',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23000,
    avatar: '刘',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷',
    specialty: '兽栏照看',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-120',
    name: '孙定川',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25000,
    avatar: '孙',
    tone: 'jade',
    group: '内门弟子',
    personality: '圆滑',
    specialty: '试炼场值守',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-121',
    name: '罗拾薪',
    title: '内门弟子',
    realm: '筑基初期',
    power: 22800,
    avatar: '罗',
    tone: 'jade',
    group: '内门弟子',
    personality: '懒散',
    specialty: '山门接待',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-122',
    name: '于斫木',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25800,
    avatar: '于',
    tone: 'jade',
    group: '内门弟子',
    personality: '好胜',
    specialty: '化形研习',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-123',
    name: '傅巡山',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31500,
    avatar: '傅',
    tone: 'jade',
    group: '内门弟子',
    personality: '孤僻',
    specialty: '灵泉看守',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-124',
    name: '崔御风',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '崔',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '药园除草',
    note: '盼着血脉觉醒入内门',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-125',
    name: '侯抱朴',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6620,
    avatar: '侯',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '矿洞运料',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-126',
    name: '汤崇德',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6740,
    avatar: '汤',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '山门扫地',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-127',
    name: '赖浣纱',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6860,
    avatar: '赖',
    tone: 'jade',
    group: '外门弟子',
    personality: '谨慎',
    specialty: '膳堂帮厨',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-128',
    name: '张步莲',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6980,
    avatar: '张',
    tone: 'jade',
    group: '外门弟子',
    personality: '寡言',
    specialty: '洗衣浆裳',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-129',
    name: '周无瑕',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '周',
    tone: 'jade',
    group: '外门弟子',
    personality: '嘴碎',
    specialty: '饲灵禽',
    note: '盼着血脉觉醒入内门',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-130',
    name: '何令仪',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6620,
    avatar: '何',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '抄录杂务',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-131',
    name: '韩慧心',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6740,
    avatar: '韩',
    tone: 'jade',
    group: '外门弟子',
    personality: '清冷',
    specialty: '传信跑腿',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-132',
    name: '袁琼华',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '袁',
    tone: 'jade',
    group: '外门弟子',
    personality: '妖冶',
    specialty: '灯油添换',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-133',
    name: '苏绿筠',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '苏',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷艳',
    specialty: '柴房劈柴',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-134',
    name: '叶黄粱',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '叶',
    tone: 'jade',
    group: '外门弟子',
    personality: '神秘',
    specialty: '水井汲水',
    note: '盼着血脉觉醒入内门',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-135',
    name: '汪金蕊',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '汪',
    tone: 'jade',
    group: '外门弟子',
    personality: '清傲',
    specialty: '菜畦施肥',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-136',
    name: '谭禾穗',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5600,
    avatar: '谭',
    tone: 'jade',
    group: '外门弟子',
    personality: '飒爽',
    specialty: '仓储盘点',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-137',
    name: '白药香',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5680,
    avatar: '白',
    tone: 'jade',
    group: '外门弟子',
    personality: '温婉',
    specialty: '院落洒扫',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-138',
    name: '顾萱草',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '顾',
    tone: 'jade',
    group: '外门弟子',
    personality: '细腻',
    specialty: '路石修补',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-139',
    name: '钱石桥',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '钱',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '试炼场擦拭',
    note: '盼着血脉觉醒入内门',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-140',
    name: '贺水衡',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '贺',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '经阁打杂',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-141',
    name: '夜霜刃',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '夜',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '丹渣清理',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-142',
    name: '赵云起',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '赵',
    tone: 'jade',
    group: '外门弟子',
    personality: '固执',
    specialty: '器屑回收',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-143',
    name: '林月白',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '林',
    tone: 'jade',
    group: '外门弟子',
    personality: '耿直',
    specialty: '灵兽粪便清理',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-144',
    name: '谢子昂',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '谢',
    tone: 'jade',
    group: '外门弟子',
    personality: '认真',
    specialty: '外门巡更',
    note: '盼着血脉觉醒入内门',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-145',
    name: '曹叔平',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '曹',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '迎客引路',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-146',
    name: '吕屠魔',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '吕',
    tone: 'jade',
    group: '外门弟子',
    personality: '热心',
    specialty: '杂物搬运',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-147',
    name: '薛断岳',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '薛',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷酷',
    specialty: '灶火添薪',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-148',
    name: '钟噬魂',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '钟',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴鸷',
    specialty: '晒药翻片',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-149',
    name: '姚煞星',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '姚',
    tone: 'jade',
    group: '外门弟子',
    personality: '沉默',
    specialty: '缝补道袍',
    note: '盼着血脉觉醒入内门',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-150',
    name: '孔怀安',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '孔',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴沉',
    specialty: '磨刀擦剑',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-151',
    name: '史致远',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '史',
    tone: 'jade',
    group: '外门弟子',
    personality: '豪迈',
    specialty: '井绳更换',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-152',
    name: '雷景行',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '雷',
    tone: 'jade',
    group: '外门弟子',
    personality: '勤恳',
    specialty: '篱笆修缮',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-153',
    name: '乔无咎',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '乔',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实',
    specialty: '账册誊抄',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-154',
    name: '任掌灯',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4900,
    avatar: '任',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '砍柴挑水',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-155',
    name: '邹启扉',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5125,
    avatar: '邹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '膳堂洗碗',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-156',
    name: '康墨池',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5351,
    avatar: '康',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '茅厕清理',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-157',
    name: '邵药香',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4988,
    avatar: '邵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '石阶洒扫',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-158',
    name: '尹萱草',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5214,
    avatar: '尹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '柴房看守',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-159',
    name: '龚蘅芷',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5439,
    avatar: '龚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '菜园浇水',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-160',
    name: '王幽萝',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5076,
    avatar: '王',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '喂养灵鸡',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-161',
    name: '吴霜姬',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5096,
    avatar: '吴',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清冷',
    specialty: '浆洗衣物',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-162',
    name: '郭鸾音',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5321,
    avatar: '郭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '妖冶',
    specialty: '运送粪肥',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-163',
    name: '唐素心',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4959,
    avatar: '唐',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷艳',
    specialty: '擦拭门扉',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-164',
    name: '邓听雨',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5184,
    avatar: '邓',
    tone: 'jade',
    group: '杂役弟子',
    personality: '神秘',
    specialty: '添换灯油',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-165',
    name: '卢疏影',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5410,
    avatar: '卢',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清傲',
    specialty: '清扫厢房',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-166',
    name: '阎怀橘',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5047,
    avatar: '阎',
    tone: 'jade',
    group: '杂役弟子',
    personality: '飒爽',
    specialty: '搬运砖石',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-167',
    name: '田浣纱',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5272,
    avatar: '田',
    tone: 'jade',
    group: '杂役弟子',
    personality: '温婉',
    specialty: '修补篱笆',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-168',
    name: '廖步莲',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5292,
    avatar: '廖',
    tone: 'jade',
    group: '杂役弟子',
    personality: '细腻',
    specialty: '井边打水',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-169',
    name: '崔无瑕',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4929,
    avatar: '崔',
    tone: 'jade',
    group: '杂役弟子',
    personality: '泼辣',
    specialty: '晒谷翻场',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-170',
    name: '侯令仪',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5155,
    avatar: '侯',
    tone: 'jade',
    group: '杂役弟子',
    personality: '聪慧',
    specialty: '灶下添薪',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-171',
    name: '汤慧心',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5380,
    avatar: '汤',
    tone: 'jade',
    group: '杂役弟子',
    personality: '内敛',
    specialty: '泔水倾倒',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-172',
    name: '赖琼华',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5018,
    avatar: '赖',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '草料堆垛',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-173',
    name: '张绿筠',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5243,
    avatar: '张',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '扫落叶',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-174',
    name: '周黄粱',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5468,
    avatar: '周',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '擦拭香案',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-175',
    name: '何问松',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4900,
    avatar: '何',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '山门扫地',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-176',
    name: '韩破晓',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5125,
    avatar: '韩',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '廊下抹灰',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-177',
    name: '袁乘风',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5351,
    avatar: '袁',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '修整竹篱',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-178',
    name: '苏栖梧',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4988,
    avatar: '苏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '翻晒被褥',
    note: '杂役年头不短，略通人情',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-179',
    name: '叶养浩',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5214,
    avatar: '叶',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '淘米择菜',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-180',
    name: '汪自强',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5439,
    avatar: '汪',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '劈柴入垛',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-181',
    name: '谭通玄',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5076,
    avatar: '谭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '清理兽栏',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-182',
    name: '白凝锋',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5096,
    avatar: '白',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '抬送柴捆',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-183',
    name: '顾安澜',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5321,
    avatar: '顾',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '整理工具',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-184',
    name: '钱行舟',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4959,
    avatar: '钱',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '巡夜敲梆',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-185',
    name: '贺担水',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5184,
    avatar: '贺',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '清晨打更',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-186',
    name: '夜守夜',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5410,
    avatar: '夜',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '帮厨切菜',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-187',
    name: '赵司仓',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5047,
    avatar: '赵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '刷洗锅灶',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-188',
    name: '林击柝',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5272,
    avatar: '林',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '搬运水缸',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-189',
    name: '谢录籍',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5292,
    avatar: '谢',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '清扫丹渣',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-190',
    name: '曹竹简',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4929,
    avatar: '曹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '收拾器屑',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-191',
    name: '吕玄戈',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5155,
    avatar: '吕',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '抄录杂单',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-192',
    name: '薛铁衣',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5380,
    avatar: '薛',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '传唤杂役',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-193',
    name: '钟火辛',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5018,
    avatar: '钟',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '看守仓门',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-194',
    name: '姚金锋',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5243,
    avatar: '姚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '修补草鞋',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-195',
    name: '孔风至',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5468,
    avatar: '孔',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '搓麻绳',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-196',
    name: '史星河',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4900,
    avatar: '史',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '晒药翻片',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-197',
    name: '雷辰光',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5125,
    avatar: '雷',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '除草松土',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-198',
    name: '乔仲远',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5351,
    avatar: '乔',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '清理水沟',
    note: '',
    attitude: '冷淡',
    sectId: 'yaozu'
  },
  {
    id: 'yz-199',
    name: '冷少游',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4988,
    avatar: '冷',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '抬轿引路',
    note: '',
    attitude: '严格',
    sectId: 'yaozu'
  },
  {
    id: 'yz-200',
    name: '黄裂空',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5214,
    avatar: '黄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '迎接访客行李',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-201',
    name: '高焚天',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5439,
    avatar: '高',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '打扫试剑场',
    note: '',
    attitude: '中立',
    sectId: 'yaozu'
  },
  {
    id: 'yz-202',
    name: '郑破军',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5076,
    avatar: '郑',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '擦拭兵器架',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'yaozu'
  },
  {
    id: 'yz-203',
    name: '程清尘',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5096,
    avatar: '程',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '收拾膳堂残羹',
    note: '',
    attitude: '友善',
    sectId: 'yaozu'
  }
]

/** 已知女性姓名（供默认头像推断） */
export const YAOZU_FEMALE_NAMES = [
  "青丘狐帝",
  "蝶母",
  "雪狐",
  "青雀",
  "小狸",
  "青禾兔",
  "小翠雀",
  "梁芙蕖",
  "宋芙蕖",
  "丁剑影",
  "杜鸾音",
  "范素心",
  "金听雨",
  "邱疏影",
  "龙怀橘",
  "赖浣纱",
  "张步莲",
  "周无瑕",
  "何令仪",
  "韩慧心",
  "袁琼华",
  "苏绿筠",
  "叶黄粱",
  "汪金蕊",
  "谭禾穗",
  "白药香",
  "顾萱草",
  "邵药香",
  "尹萱草",
  "龚蘅芷",
  "王幽萝",
  "吴霜姬",
  "郭鸾音",
  "唐素心",
  "邓听雨",
  "卢疏影",
  "阎怀橘",
  "田浣纱",
  "廖步莲",
  "崔无瑕",
  "侯令仪",
  "汤慧心",
  "赖琼华",
  "张绿筠",
  "周黄粱"
] as const
