import type { CatalogMember } from './member-catalog'

/** 万剑宗人物名录（结构对齐青云宗；圣地战力整体偏高） */
export const WANJIAN_MEMBERS: CatalogMember[] = [
  {
    id: 'wj-1',
    name: '剑无涯',
    title: '万剑宗宗主',
    realm: '炼虚后期',
    power: 480000,
    avatar: '剑',
    tone: 'mp',
    group: '宗主',
    personality: '清傲、威严',
    specialty: '剑道、破法',
    note: '一剑破万法，威震诸域',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-2',
    name: '霜华剑尊',
    title: '副宗主',
    realm: '炼虚中期',
    power: 420000,
    avatar: '霜',
    tone: 'mp',
    group: '宗主',
    personality: '冷静、锐利',
    specialty: '冰剑、剑意',
    note: '剑心如霜，不近人情',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-3',
    name: '丹剑真人',
    title: '大长老',
    realm: '化神后期',
    power: 280000,
    avatar: '丹',
    tone: 'mp',
    group: '长老',
    personality: '严厉、古板',
    specialty: '剑丹、炼丹',
    note: '以剑入丹，独树一帜',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-4',
    name: '青莲剑娘',
    title: '二长老',
    realm: '化神中期',
    power: 250000,
    avatar: '青',
    tone: 'mp',
    group: '长老',
    personality: '温婉、聪慧',
    specialty: '灵药、医剑',
    note: '药园亦藏剑冢一角',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-5',
    name: '铸剑山人',
    title: '三长老',
    realm: '化神后期',
    power: 275000,
    avatar: '铸',
    tone: 'mp',
    group: '长老',
    personality: '豪爽、直率',
    specialty: '炼器、铸剑',
    note: '万剑峰器阁掌炉',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-6',
    name: '玄阵剑客',
    title: '四长老',
    realm: '化神中期',
    power: 248000,
    avatar: '玄',
    tone: 'mp',
    group: '长老',
    personality: '神秘、寡言',
    specialty: '剑阵、推演',
    note: '万剑护宗大阵由其主持',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-7',
    name: '醉剑仙',
    title: '五长老',
    realm: '化神初期',
    power: 210000,
    avatar: '醉',
    tone: 'mp',
    group: '长老',
    personality: '懒散、爱喝酒',
    specialty: '醉剑、剑意',
    note: '醉时剑势无人能测',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-8',
    name: '律剑长老',
    title: '执法长老',
    realm: '化神初期',
    power: 215000,
    avatar: '律',
    tone: 'mp',
    group: '长老',
    personality: '铁面无私',
    specialty: '审讯、剑律',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-9',
    name: '断罪剑使',
    title: '执法堂堂主',
    realm: '元婴后期',
    power: 150000,
    avatar: '断',
    tone: 'hp',
    group: '执事',
    personality: '冷酷、公正',
    specialty: '执法、剑术',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-10',
    name: '簿剑执事',
    title: '杂务执事',
    realm: '元婴初期',
    power: 105000,
    avatar: '簿',
    tone: 'jade',
    group: '执事',
    personality: '勤恳、琐碎',
    specialty: '庶务、账册',
    note: '经手外门杂役调配',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-11',
    name: '凌霄剑子',
    title: '亲传弟子',
    realm: '元婴初期',
    power: 108000,
    avatar: '凌',
    tone: 'gold',
    group: '亲传弟子',
    personality: '清傲、好胜',
    specialty: '御剑术',
    note: '宗主亲传，锋芒初露',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-12',
    name: '霜月',
    title: '亲传弟子',
    realm: '金丹大圆满',
    power: 92000,
    avatar: '霜',
    tone: 'gold',
    group: '亲传弟子',
    personality: '温婉、聪慧',
    specialty: '冰剑心法',
    note: '副宗主座下亲传',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-13',
    name: '烈锋',
    title: '执法弟子',
    realm: '金丹后期',
    power: 82000,
    avatar: '烈',
    tone: 'hp',
    group: '内门弟子',
    personality: '暴躁',
    specialty: '近战剑术',
    note: '',
    attitude: '容易与玩家冲突',
    sectId: 'wanjian'
  },
  {
    id: 'wj-14',
    name: '追影',
    title: '执法弟子',
    realm: '金丹中期',
    power: 72000,
    avatar: '追',
    tone: 'hp',
    group: '内门弟子',
    personality: '认真',
    specialty: '调查、追踪',
    note: '',
    attitude: '对玩家较友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-15',
    name: '石剑',
    title: '内门弟子',
    realm: '金丹初期',
    power: 62000,
    avatar: '石',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉稳、寡言',
    specialty: '重剑防御',
    note: '常年镇守万剑峰后山',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-16',
    name: '小剑童',
    title: '外门弟子',
    realm: '筑基后期',
    power: 32000,
    avatar: '小',
    tone: 'jade',
    group: '外门弟子',
    personality: '活泼、热心',
    specialty: '跑腿打听',
    note: '消息灵通',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-17',
    name: '青禾',
    title: '外门弟子',
    realm: '筑基中期',
    power: 27000,
    avatar: '青',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实、勤勉',
    specialty: '药园劳作',
    note: '一心想入内门',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-18',
    name: '阿锋',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6800,
    avatar: '阿',
    tone: 'jade',
    group: '杂役弟子',
    personality: '憨厚',
    specialty: '砍柴挑水',
    note: '宗门杂役数年',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-19',
    name: '小翠剑',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5800,
    avatar: '翠',
    tone: 'jade',
    group: '杂役弟子',
    personality: '机灵、嘴碎',
    specialty: '洒扫、传话',
    note: '常在膳堂附近转悠',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-101',
    name: '李清尘',
    title: '丹阁执事',
    realm: '元婴中期',
    power: 125000,
    avatar: '李',
    tone: 'jade',
    group: '执事',
    personality: '圆滑',
    specialty: '剑丹调配、丹房巡察',
    note: '协理大长老丹事',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-102',
    name: '徐明远',
    title: '器阁执事',
    realm: '元婴初期',
    power: 108000,
    avatar: '徐',
    tone: 'jade',
    group: '执事',
    personality: '懒散',
    specialty: '剑胚清点、铸剑后勤',
    note: '常与三长老往来',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-103',
    name: '马芙蕖',
    title: '外门执事',
    realm: '元婴初期',
    power: 102000,
    avatar: '马',
    tone: 'jade',
    group: '执事',
    personality: '认真',
    specialty: '外门考勤、弟子调度',
    note: '外门弟子多惧其簿册',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-104',
    name: '孙明远',
    title: '亲传弟子',
    realm: '金丹后期',
    power: 85000,
    avatar: '孙',
    tone: 'gold',
    group: '亲传弟子',
    personality: '认真',
    specialty: '剑丹入门',
    note: '大长老座下亲传',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-105',
    name: '罗芙蕖',
    title: '亲传弟子',
    realm: '金丹中期',
    power: 74000,
    avatar: '罗',
    tone: 'gold',
    group: '亲传弟子',
    personality: '随和',
    specialty: '医剑、灵药',
    note: '二长老座下亲传',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-106',
    name: '于若虚',
    title: '亲传弟子',
    realm: '金丹中期',
    power: 72000,
    avatar: '于',
    tone: 'gold',
    group: '亲传弟子',
    personality: '热心',
    specialty: '铸剑锤锻',
    note: '三长老座下亲传',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-107',
    name: '傅正阳',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 64000,
    avatar: '傅',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷酷',
    specialty: '剑阵推演',
    note: '四长老座下亲传',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-108',
    name: '蔡剑影',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 65000,
    avatar: '蔡',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷艳',
    specialty: '剑律、审讯',
    note: '执法长老座下亲传',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-109',
    name: '冯知微',
    title: '内门弟子',
    realm: '金丹后期',
    power: 80000,
    avatar: '冯',
    tone: 'jade',
    group: '内门弟子',
    personality: '冷静',
    specialty: '剑术勤修',
    note: '有望冲击亲传考核',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-110',
    name: '许有恒',
    title: '内门弟子',
    realm: '金丹后期',
    power: 80800,
    avatar: '许',
    tone: 'jade',
    group: '内门弟子',
    personality: '狂傲',
    specialty: '符箓抄写',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-111',
    name: '蒋望川',
    title: '内门弟子',
    realm: '金丹后期',
    power: 81600,
    avatar: '蒋',
    tone: 'jade',
    group: '内门弟子',
    personality: '嗜杀',
    specialty: '护峰巡逻',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-112',
    name: '余鸾音',
    title: '内门弟子',
    realm: '金丹后期',
    power: 82400,
    avatar: '余',
    tone: 'jade',
    group: '内门弟子',
    personality: '娇蛮',
    specialty: '藏经整理',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-113',
    name: '任素心',
    title: '内门弟子',
    realm: '金丹后期',
    power: 80000,
    avatar: '任',
    tone: 'jade',
    group: '内门弟子',
    personality: '阴柔',
    specialty: '丹房助手',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-114',
    name: '邹听雨',
    title: '内门弟子',
    realm: '金丹中期',
    power: 70000,
    avatar: '邹',
    tone: 'jade',
    group: '内门弟子',
    personality: '残忍',
    specialty: '器房学徒',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-115',
    name: '康疏影',
    title: '内门弟子',
    realm: '金丹中期',
    power: 70600,
    avatar: '康',
    tone: 'jade',
    group: '内门弟子',
    personality: '机灵',
    specialty: '阵基维护',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-116',
    name: '邵怀橘',
    title: '内门弟子',
    realm: '金丹中期',
    power: 71200,
    avatar: '邵',
    tone: 'jade',
    group: '内门弟子',
    personality: '文静',
    specialty: '灵田督耕',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-117',
    name: '尹厚德',
    title: '内门弟子',
    realm: '金丹中期',
    power: 71800,
    avatar: '尹',
    tone: 'jade',
    group: '内门弟子',
    personality: '谨慎',
    specialty: '外勤传讯',
    note: '有望冲击亲传考核',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-118',
    name: '龚悟真',
    title: '内门弟子',
    realm: '金丹中期',
    power: 72400,
    avatar: '龚',
    tone: 'jade',
    group: '内门弟子',
    personality: '嘴碎',
    specialty: '内务协理',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-119',
    name: '王铸剑',
    title: '内门弟子',
    realm: '金丹初期',
    power: 60000,
    avatar: '王',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷',
    specialty: '剑灵照看',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-120',
    name: '吴定川',
    title: '内门弟子',
    realm: '金丹初期',
    power: 60500,
    avatar: '吴',
    tone: 'jade',
    group: '内门弟子',
    personality: '圆滑',
    specialty: '试剑场值守',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-121',
    name: '郭拾薪',
    title: '内门弟子',
    realm: '金丹初期',
    power: 61000,
    avatar: '郭',
    tone: 'jade',
    group: '内门弟子',
    personality: '懒散',
    specialty: '山门接待',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-122',
    name: '唐斫木',
    title: '内门弟子',
    realm: '金丹初期',
    power: 61500,
    avatar: '唐',
    tone: 'jade',
    group: '内门弟子',
    personality: '好胜',
    specialty: '剑意研习',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-123',
    name: '邓巡山',
    title: '内门弟子',
    realm: '金丹初期',
    power: 62000,
    avatar: '邓',
    tone: 'jade',
    group: '内门弟子',
    personality: '孤僻',
    specialty: '灵泉看守',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-124',
    name: '孔御风',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31000,
    avatar: '孔',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '药园除草',
    note: '盼着年底剑试翻身',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-125',
    name: '史抱朴',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31400,
    avatar: '史',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '矿洞运料',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-126',
    name: '雷崇德',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31800,
    avatar: '雷',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '山门扫地',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-127',
    name: '乔浣纱',
    title: '外门弟子',
    realm: '筑基后期',
    power: 32200,
    avatar: '乔',
    tone: 'jade',
    group: '外门弟子',
    personality: '谨慎',
    specialty: '膳堂帮厨',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-128',
    name: '冷步莲',
    title: '外门弟子',
    realm: '筑基后期',
    power: 32600,
    avatar: '冷',
    tone: 'jade',
    group: '外门弟子',
    personality: '寡言',
    specialty: '洗衣浆裳',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-129',
    name: '黄无瑕',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31000,
    avatar: '黄',
    tone: 'jade',
    group: '外门弟子',
    personality: '嘴碎',
    specialty: '饲灵禽',
    note: '盼着年底剑试翻身',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-130',
    name: '高令仪',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31400,
    avatar: '高',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '抄录杂务',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-131',
    name: '郑慧心',
    title: '外门弟子',
    realm: '筑基后期',
    power: 31800,
    avatar: '郑',
    tone: 'jade',
    group: '外门弟子',
    personality: '清冷',
    specialty: '传信跑腿',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-132',
    name: '程琼华',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26600,
    avatar: '程',
    tone: 'jade',
    group: '外门弟子',
    personality: '妖冶',
    specialty: '灯油添换',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-133',
    name: '彭绿筠',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26900,
    avatar: '彭',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷艳',
    specialty: '柴房劈柴',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-134',
    name: '魏黄粱',
    title: '外门弟子',
    realm: '筑基中期',
    power: 27200,
    avatar: '魏',
    tone: 'jade',
    group: '外门弟子',
    personality: '神秘',
    specialty: '水井汲水',
    note: '盼着年底剑试翻身',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-135',
    name: '夏金蕊',
    title: '外门弟子',
    realm: '筑基中期',
    power: 27500,
    avatar: '夏',
    tone: 'jade',
    group: '外门弟子',
    personality: '清傲',
    specialty: '菜畦施肥',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-136',
    name: '石禾穗',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26000,
    avatar: '石',
    tone: 'jade',
    group: '外门弟子',
    personality: '飒爽',
    specialty: '仓储盘点',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-137',
    name: '郝药香',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26300,
    avatar: '郝',
    tone: 'jade',
    group: '外门弟子',
    personality: '温婉',
    specialty: '院落洒扫',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-138',
    name: '江萱草',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26600,
    avatar: '江',
    tone: 'jade',
    group: '外门弟子',
    personality: '细腻',
    specialty: '路石修补',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-139',
    name: '段石桥',
    title: '外门弟子',
    realm: '筑基中期',
    power: 26900,
    avatar: '段',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '试剑场擦拭',
    note: '盼着年底剑试翻身',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-140',
    name: '武水衡',
    title: '外门弟子',
    realm: '筑基中期',
    power: 27200,
    avatar: '武',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '经阁打杂',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-141',
    name: '墨霜刃',
    title: '外门弟子',
    realm: '筑基中期',
    power: 27500,
    avatar: '墨',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '丹渣清理',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-142',
    name: '杨云起',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22750,
    avatar: '杨',
    tone: 'jade',
    group: '外门弟子',
    personality: '固执',
    specialty: '器屑回收',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-143',
    name: '朱月白',
    title: '外门弟子',
    realm: '筑基初期',
    power: 23000,
    avatar: '朱',
    tone: 'jade',
    group: '外门弟子',
    personality: '耿直',
    specialty: '灵兽粪便清理',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-144',
    name: '宋子昂',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22000,
    avatar: '宋',
    tone: 'jade',
    group: '外门弟子',
    personality: '认真',
    specialty: '外门巡更',
    note: '盼着年底剑试翻身',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-145',
    name: '萧叔平',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22250,
    avatar: '萧',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '迎客引路',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-146',
    name: '曾屠魔',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22500,
    avatar: '曾',
    tone: 'jade',
    group: '外门弟子',
    personality: '热心',
    specialty: '杂物搬运',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-147',
    name: '丁断岳',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22750,
    avatar: '丁',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷酷',
    specialty: '灶火添薪',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-148',
    name: '戴噬魂',
    title: '外门弟子',
    realm: '筑基初期',
    power: 23000,
    avatar: '戴',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴鸷',
    specialty: '晒药翻片',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-149',
    name: '方煞星',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22000,
    avatar: '方',
    tone: 'jade',
    group: '外门弟子',
    personality: '沉默',
    specialty: '缝补道袍',
    note: '盼着年底剑试翻身',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-150',
    name: '陆怀安',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22250,
    avatar: '陆',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴沉',
    specialty: '磨刀擦剑',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-151',
    name: '秦致远',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22500,
    avatar: '秦',
    tone: 'jade',
    group: '外门弟子',
    personality: '豪迈',
    specialty: '井绳更换',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-152',
    name: '万景行',
    title: '外门弟子',
    realm: '筑基初期',
    power: 22750,
    avatar: '万',
    tone: 'jade',
    group: '外门弟子',
    personality: '勤恳',
    specialty: '篱笆修缮',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-153',
    name: '常无咎',
    title: '外门弟子',
    realm: '筑基初期',
    power: 23000,
    avatar: '常',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实',
    specialty: '账册誊抄',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-154',
    name: '汪掌灯',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '汪',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '砍柴挑水',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-155',
    name: '谭启扉',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6600,
    avatar: '谭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '膳堂洗碗',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-156',
    name: '白墨池',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6700,
    avatar: '白',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '茅厕清理',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-157',
    name: '顾药香',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6800,
    avatar: '顾',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '石阶洒扫',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-158',
    name: '钱萱草',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6900,
    avatar: '钱',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '柴房看守',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-159',
    name: '贺蘅芷',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '贺',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '菜园浇水',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-160',
    name: '夜幽萝',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6600,
    avatar: '夜',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '喂养灵鸡',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-161',
    name: '赵霜姬',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6700,
    avatar: '赵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清冷',
    specialty: '浆洗衣物',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-162',
    name: '林鸾音',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6800,
    avatar: '林',
    tone: 'jade',
    group: '杂役弟子',
    personality: '妖冶',
    specialty: '运送粪肥',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-163',
    name: '谢素心',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6900,
    avatar: '谢',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷艳',
    specialty: '擦拭门扉',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-164',
    name: '曹听雨',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '曹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '神秘',
    specialty: '添换灯油',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-165',
    name: '吕疏影',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6600,
    avatar: '吕',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清傲',
    specialty: '清扫厢房',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-166',
    name: '薛怀橘',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6700,
    avatar: '薛',
    tone: 'jade',
    group: '杂役弟子',
    personality: '飒爽',
    specialty: '搬运砖石',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-167',
    name: '钟浣纱',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6800,
    avatar: '钟',
    tone: 'jade',
    group: '杂役弟子',
    personality: '温婉',
    specialty: '修补篱笆',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-168',
    name: '姚步莲',
    title: '杂役弟子',
    realm: '炼气后期',
    power: 6900,
    avatar: '姚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '细腻',
    specialty: '井边打水',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-169',
    name: '孔无瑕',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '孔',
    tone: 'jade',
    group: '杂役弟子',
    personality: '泼辣',
    specialty: '晒谷翻场',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-170',
    name: '史令仪',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '史',
    tone: 'jade',
    group: '杂役弟子',
    personality: '聪慧',
    specialty: '灶下添薪',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-171',
    name: '雷慧心',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '雷',
    tone: 'jade',
    group: '杂役弟子',
    personality: '内敛',
    specialty: '泔水倾倒',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-172',
    name: '乔琼华',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5600,
    avatar: '乔',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '草料堆垛',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-173',
    name: '冷绿筠',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5680,
    avatar: '冷',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '扫落叶',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-174',
    name: '黄黄粱',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '黄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '擦拭香案',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-175',
    name: '高问松',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '高',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '山门扫地',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-176',
    name: '郑破晓',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '郑',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '廊下抹灰',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-177',
    name: '程乘风',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '程',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '修整竹篱',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-178',
    name: '彭栖梧',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5600,
    avatar: '彭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '翻晒被褥',
    note: '杂役年头不短，略通人情',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-179',
    name: '魏养浩',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5680,
    avatar: '魏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '淘米择菜',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-180',
    name: '夏自强',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '夏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '劈柴入垛',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-181',
    name: '石通玄',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '石',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '清理兽栏',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-182',
    name: '郝凝锋',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '郝',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '抬送柴捆',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-183',
    name: '江安澜',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '江',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '整理工具',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-184',
    name: '段行舟',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5600,
    avatar: '段',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '巡夜敲梆',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-185',
    name: '武担水',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5680,
    avatar: '武',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '清晨打更',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-186',
    name: '墨守夜',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '墨',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '帮厨切菜',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-187',
    name: '杨司仓',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '杨',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '刷洗锅灶',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-188',
    name: '朱击柝',
    title: '杂役弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '朱',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '搬运水缸',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-189',
    name: '宋录籍',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '宋',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '清扫丹渣',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-190',
    name: '萧竹简',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '萧',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '收拾器屑',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-191',
    name: '曾玄戈',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '曾',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '抄录杂单',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-192',
    name: '丁铁衣',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '丁',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '传唤杂役',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-193',
    name: '戴火辛',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '戴',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '看守仓门',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-194',
    name: '方金锋',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '方',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '修补草鞋',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-195',
    name: '陆风至',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '陆',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '搓麻绳',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-196',
    name: '秦星河',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '秦',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '晒药翻片',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-197',
    name: '万辰光',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '万',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '除草松土',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-198',
    name: '常仲远',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '常',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '清理水沟',
    note: '',
    attitude: '冷淡',
    sectId: 'wanjian'
  },
  {
    id: 'wj-199',
    name: '狄少游',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '狄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '抬轿引路',
    note: '',
    attitude: '严格',
    sectId: 'wanjian'
  },
  {
    id: 'wj-200',
    name: '陈裂空',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '陈',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '迎接访客行李',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-201',
    name: '胡焚天',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '胡',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '打扫试剑场',
    note: '',
    attitude: '中立',
    sectId: 'wanjian'
  },
  {
    id: 'wj-202',
    name: '梁破军',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '梁',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '擦拭兵器架',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'wanjian'
  },
  {
    id: 'wj-203',
    name: '董清尘',
    title: '杂役弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '董',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '收拾膳堂残羹',
    note: '',
    attitude: '友善',
    sectId: 'wanjian'
  }
]

/** 已知女性姓名（供默认头像推断） */
export { WANJIAN_FEMALE_NAMES } from './member-female-names'
