/** 青云宗扩编弟子（执事/亲传/内门/外门/杂役） */
export const QINGYUN_EXTRA_MEMBERS = [
  {
    id: 'qy-101',
    name: '刘无咎',
    title: '丹阁执事',
    realm: '金丹中期',
    power: 72000,
    avatar: '刘',
    tone: 'jade',
    group: '执事',
    personality: '寡言',
    specialty: '丹方调配、丹房巡察',
    note: '协理二长老药事',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-102',
    name: '孙朝晖',
    title: '器阁执事',
    realm: '金丹初期',
    power: 63000,
    avatar: '孙',
    tone: 'jade',
    group: '执事',
    personality: '憨厚',
    specialty: '矿料清点、炼器后勤',
    note: '常与三长老往来',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-103',
    name: '罗疏影',
    title: '外门执事',
    realm: '金丹初期',
    power: 60000,
    avatar: '罗',
    tone: 'jade',
    group: '执事',
    personality: '柔和',
    specialty: '外门考勤、弟子调度',
    note: '外门弟子多惧其簿册',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-104',
    name: '胡朝晖',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 58000,
    avatar: '胡',
    tone: 'gold',
    group: '亲传弟子',
    personality: '急躁',
    specialty: '炼丹入门',
    note: '大长老座下亲传',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-105',
    name: '梁疏影',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 36000,
    avatar: '梁',
    tone: 'gold',
    group: '亲传弟子',
    personality: '聪慧',
    specialty: '医理、灵药',
    note: '二长老座下亲传',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-106',
    name: '董破晓',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 34000,
    avatar: '董',
    tone: 'gold',
    group: '亲传弟子',
    personality: '爽朗',
    specialty: '炼器锤锻',
    note: '三长老座下亲传',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-107',
    name: '沈乘风',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 32000,
    avatar: '沈',
    tone: 'gold',
    group: '亲传弟子',
    personality: '固执',
    specialty: '阵法推演',
    note: '四长老座下亲传',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-108',
    name: '贾步莲',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 33000,
    avatar: '贾',
    tone: 'gold',
    group: '亲传弟子',
    personality: '寡言',
    specialty: '律法、审讯',
    note: '执法长老座下亲传',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-109',
    name: '于执炬',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31000,
    avatar: '于',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷',
    specialty: '剑术勤修',
    note: '有望冲击亲传考核',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-110',
    name: '傅踏雪',
    title: '内门弟子',
    realm: '筑基后期',
    power: 30000,
    avatar: '傅',
    tone: 'jade',
    group: '内门弟子',
    personality: '圆滑',
    specialty: '符箓抄写',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-111',
    name: '蔡凌云',
    title: '内门弟子',
    realm: '筑基中期',
    power: 27000,
    avatar: '蔡',
    tone: 'jade',
    group: '内门弟子',
    personality: '懒散',
    specialty: '护山巡逻',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-112',
    name: '潘如玉',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26500,
    avatar: '潘',
    tone: 'jade',
    group: '内门弟子',
    personality: '认真',
    specialty: '藏经整理',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-113',
    name: '姜柔嘉',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26000,
    avatar: '姜',
    tone: 'jade',
    group: '内门弟子',
    personality: '倔强',
    specialty: '丹房助手',
    note: '有望冲击亲传考核',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-114',
    name: '熊窈窕',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24500,
    avatar: '熊',
    tone: 'jade',
    group: '内门弟子',
    personality: '活泼',
    specialty: '器房学徒',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-115',
    name: '毛瑶光',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24000,
    avatar: '毛',
    tone: 'jade',
    group: '内门弟子',
    personality: '机灵',
    specialty: '阵基维护',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-116',
    name: '孟紫烟',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23500,
    avatar: '孟',
    tone: 'jade',
    group: '内门弟子',
    personality: '文静',
    specialty: '灵田督耕',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-117',
    name: '黎济世',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25500,
    avatar: '黎',
    tone: 'jade',
    group: '内门弟子',
    personality: '谨慎',
    specialty: '外勤传讯',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-118',
    name: '文负囊',
    title: '内门弟子',
    realm: '筑基后期',
    power: 30500,
    avatar: '文',
    tone: 'jade',
    group: '内门弟子',
    personality: '嘴碎',
    specialty: '内务协理',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-119',
    name: '赵理田',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23000,
    avatar: '赵',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷',
    specialty: '兽栏照看',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-120',
    name: '林护阶',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25000,
    avatar: '林',
    tone: 'jade',
    group: '内门弟子',
    personality: '圆滑',
    specialty: '试剑场值守',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-121',
    name: '谢鸣铎',
    title: '内门弟子',
    realm: '筑基初期',
    power: 22800,
    avatar: '谢',
    tone: 'jade',
    group: '内门弟子',
    personality: '懒散',
    specialty: '山门接待',
    note: '有望冲击亲传考核',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-122',
    name: '曹封篆',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25800,
    avatar: '曹',
    tone: 'jade',
    group: '内门弟子',
    personality: '好胜',
    specialty: '功法研习',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-123',
    name: '吕砚边',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31500,
    avatar: '吕',
    tone: 'jade',
    group: '内门弟子',
    personality: '孤僻',
    specialty: '灵泉看守',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-124',
    name: '白载物',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '白',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '药园除草',
    note: '盼着年底外门大比翻身',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-125',
    name: '顾炼心',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6620,
    avatar: '顾',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '矿洞运料',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-126',
    name: '钱镇岳',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6740,
    avatar: '钱',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '山门扫地',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-127',
    name: '贺白芷',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6860,
    avatar: '贺',
    tone: 'jade',
    group: '外门弟子',
    personality: '谨慎',
    specialty: '膳堂帮厨',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-128',
    name: '陈银杏',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6980,
    avatar: '陈',
    tone: 'jade',
    group: '外门弟子',
    personality: '寡言',
    specialty: '洗衣浆裳',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-129',
    name: '胡水仙',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6500,
    avatar: '胡',
    tone: 'jade',
    group: '外门弟子',
    personality: '嘴碎',
    specialty: '饲灵禽',
    note: '盼着年底外门大比翻身',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-130',
    name: '梁茶烟',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6620,
    avatar: '梁',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '抄录杂务',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-131',
    name: '董芷柔',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6740,
    avatar: '董',
    tone: 'jade',
    group: '外门弟子',
    personality: '清冷',
    specialty: '传信跑腿',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-132',
    name: '沈蘅芜',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '沈',
    tone: 'jade',
    group: '外门弟子',
    personality: '温婉',
    specialty: '灯油添换',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-133',
    name: '贾素心',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '贾',
    tone: 'jade',
    group: '外门弟子',
    personality: '细腻',
    specialty: '柴房劈柴',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-134',
    name: '杜听雨',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '杜',
    tone: 'jade',
    group: '外门弟子',
    personality: '泼辣',
    specialty: '水井汲水',
    note: '盼着年底外门大比翻身',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-135',
    name: '范疏影',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '范',
    tone: 'jade',
    group: '外门弟子',
    personality: '聪慧',
    specialty: '菜畦施肥',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-136',
    name: '金怀橘',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5600,
    avatar: '金',
    tone: 'jade',
    group: '外门弟子',
    personality: '内敛',
    specialty: '仓储盘点',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-137',
    name: '邱浣纱',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5680,
    avatar: '邱',
    tone: 'jade',
    group: '外门弟子',
    personality: '谨慎',
    specialty: '院落洒扫',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-138',
    name: '龙步莲',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5760,
    avatar: '龙',
    tone: 'jade',
    group: '外门弟子',
    personality: '寡言',
    specialty: '路石修补',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-139',
    name: '易雨歇',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5840,
    avatar: '易',
    tone: 'jade',
    group: '外门弟子',
    personality: '认真',
    specialty: '试剑场擦拭',
    note: '盼着年底外门大比翻身',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-140',
    name: '张日升',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5920,
    avatar: '张',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '经阁打杂',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-141',
    name: '周伯庸',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6000,
    avatar: '周',
    tone: 'jade',
    group: '外门弟子',
    personality: '热心',
    specialty: '丹渣清理',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-142',
    name: '何季恒',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '何',
    tone: 'jade',
    group: '外门弟子',
    personality: '勤恳',
    specialty: '器屑回收',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-143',
    name: '韩清尘',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '韩',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实',
    specialty: '灵兽粪便清理',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-144',
    name: '袁明远',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '袁',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '外门巡更',
    note: '盼着年底外门大比翻身',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-145',
    name: '苏立恒',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '苏',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '迎客引路',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-146',
    name: '叶若虚',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '叶',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '杂物搬运',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-147',
    name: '汪正阳',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '汪',
    tone: 'jade',
    group: '外门弟子',
    personality: '固执',
    specialty: '灶火添薪',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-148',
    name: '谭听潮',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '谭',
    tone: 'jade',
    group: '外门弟子',
    personality: '耿直',
    specialty: '晒药翻片',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-149',
    name: '白执炬',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4800,
    avatar: '白',
    tone: 'jade',
    group: '外门弟子',
    personality: '认真',
    specialty: '缝补道袍',
    note: '盼着年底外门大比翻身',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-150',
    name: '顾踏雪',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4860,
    avatar: '顾',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '磨刀擦剑',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-151',
    name: '钱凌云',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4920,
    avatar: '钱',
    tone: 'jade',
    group: '外门弟子',
    personality: '热心',
    specialty: '井绳更换',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-152',
    name: '贺守拙',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4980,
    avatar: '贺',
    tone: 'jade',
    group: '外门弟子',
    personality: '勤恳',
    specialty: '篱笆修缮',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-153',
    name: '陈弘毅',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5040,
    avatar: '陈',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实',
    specialty: '账册誊抄',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-154',
    name: '石白羽',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5000,
    avatar: '石',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '砍柴挑水',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-155',
    name: '郝苍岚',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5230,
    avatar: '郝',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '膳堂洗碗',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-156',
    name: '江木青',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5460,
    avatar: '江',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '茅厕清理',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-157',
    name: '段浣纱',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5090,
    avatar: '段',
    tone: 'jade',
    group: '杂役弟子',
    personality: '温婉',
    specialty: '石阶洒扫',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-158',
    name: '武步莲',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5320,
    avatar: '武',
    tone: 'jade',
    group: '杂役弟子',
    personality: '细腻',
    specialty: '柴房看守',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-159',
    name: '李无瑕',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5550,
    avatar: '李',
    tone: 'jade',
    group: '杂役弟子',
    personality: '泼辣',
    specialty: '菜园浇水',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-160',
    name: '徐令仪',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5180,
    avatar: '徐',
    tone: 'jade',
    group: '杂役弟子',
    personality: '聪慧',
    specialty: '喂养灵鸡',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-161',
    name: '马慧心',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5200,
    avatar: '马',
    tone: 'jade',
    group: '杂役弟子',
    personality: '内敛',
    specialty: '浆洗衣物',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-162',
    name: '冯琼华',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5430,
    avatar: '冯',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '运送粪肥',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-163',
    name: '许绿筠',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5060,
    avatar: '许',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '擦拭门扉',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-164',
    name: '蒋黄粱',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5290,
    avatar: '蒋',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '添换灯油',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-165',
    name: '余金蕊',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5520,
    avatar: '余',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '清扫厢房',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-166',
    name: '任禾穗',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5150,
    avatar: '任',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清冷',
    specialty: '搬运砖石',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-167',
    name: '邹药香',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5380,
    avatar: '邹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '温婉',
    specialty: '修补篱笆',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-168',
    name: '康萱草',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5400,
    avatar: '康',
    tone: 'jade',
    group: '杂役弟子',
    personality: '细腻',
    specialty: '井边打水',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-169',
    name: '邵蘅芷',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5030,
    avatar: '邵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '泼辣',
    specialty: '晒谷翻场',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-170',
    name: '尹婉清',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5260,
    avatar: '尹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '聪慧',
    specialty: '灶下添薪',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-171',
    name: '龚含烟',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5490,
    avatar: '龚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '内敛',
    specialty: '泔水倾倒',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-172',
    name: '黄流云',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5120,
    avatar: '黄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '草料堆垛',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-173',
    name: '高弄梅',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5350,
    avatar: '高',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '扫落叶',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-174',
    name: '郑织锦',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5580,
    avatar: '郑',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '擦拭香案',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-175',
    name: '程炼心',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5000,
    avatar: '程',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '山门扫地',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-176',
    name: '彭镇岳',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5230,
    avatar: '彭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '廊下抹灰',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-177',
    name: '魏济世',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5460,
    avatar: '魏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '修整竹篱',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-178',
    name: '夏负囊',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5090,
    avatar: '夏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '翻晒被褥',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-179',
    name: '石理田',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5320,
    avatar: '石',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '淘米择菜',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-180',
    name: '郝护阶',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5550,
    avatar: '郝',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '劈柴入垛',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-181',
    name: '江鸣铎',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5180,
    avatar: '江',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '清理兽栏',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-182',
    name: '段封篆',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5200,
    avatar: '段',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '抬送柴捆',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-183',
    name: '武砚边',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5430,
    avatar: '武',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '整理工具',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-184',
    name: '李白羽',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5060,
    avatar: '李',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '巡夜敲梆',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-185',
    name: '徐苍岚',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5290,
    avatar: '徐',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '清晨打更',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-186',
    name: '马木青',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5520,
    avatar: '马',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '帮厨切菜',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-187',
    name: '冯土厚',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5150,
    avatar: '冯',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '刷洗锅灶',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-188',
    name: '许雷霆',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5380,
    avatar: '许',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '搬运水缸',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-189',
    name: '蒋雨歇',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5400,
    avatar: '蒋',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '清扫丹渣',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-190',
    name: '余日升',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5030,
    avatar: '余',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '收拾器屑',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-191',
    name: '任伯庸',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5260,
    avatar: '任',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '抄录杂单',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-192',
    name: '邹季恒',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5490,
    avatar: '邹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '传唤杂役',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-193',
    name: '康清尘',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5120,
    avatar: '康',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '看守仓门',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-194',
    name: '邵明远',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5350,
    avatar: '邵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '修补草鞋',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-195',
    name: '尹立恒',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5580,
    avatar: '尹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '搓麻绳',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-196',
    name: '龚若虚',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5000,
    avatar: '龚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '晒药翻片',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-197',
    name: '黄正阳',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5230,
    avatar: '黄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '除草松土',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-198',
    name: '高听潮',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5460,
    avatar: '高',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '清理水沟',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-199',
    name: '郑执炬',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5090,
    avatar: '郑',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '抬轿引路',
    note: '',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-200',
    name: '程踏雪',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5320,
    avatar: '程',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '迎接访客行李',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  },
  {
    id: 'qy-201',
    name: '彭凌云',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5550,
    avatar: '彭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '打扫试剑场',
    note: '',
    attitude: '中立',
    sectId: 'qingyun'
  },
  {
    id: 'qy-202',
    name: '魏守拙',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5180,
    avatar: '魏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '擦拭兵器架',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'qingyun'
  },
  {
    id: 'qy-203',
    name: '夏弘毅',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5200,
    avatar: '夏',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '收拾膳堂残羹',
    note: '',
    attitude: '友善',
    sectId: 'qingyun'
  }
]

/** 扩编中已知女性姓名（供默认头像推断） */
export const QINGYUN_EXTRA_FEMALE_NAMES = [
  "罗疏影",
  "梁疏影",
  "贾步莲",
  "潘如玉",
  "姜柔嘉",
  "熊窈窕",
  "毛瑶光",
  "孟紫烟",
  "贺白芷",
  "陈银杏",
  "胡水仙",
  "梁茶烟",
  "董芷柔",
  "沈蘅芜",
  "贾素心",
  "杜听雨",
  "范疏影",
  "金怀橘",
  "邱浣纱",
  "龙步莲",
  "段浣纱",
  "武步莲",
  "李无瑕",
  "徐令仪",
  "马慧心",
  "冯琼华",
  "许绿筠",
  "蒋黄粱",
  "余金蕊",
  "任禾穗",
  "邹药香",
  "康萱草",
  "邵蘅芷",
  "尹婉清",
  "龚含烟",
  "黄流云",
  "高弄梅",
  "郑织锦"
] as const
