import type { CatalogMember } from './member-catalog'

/** 天魔宗人物名录（结构对齐青云宗） */
export const TIANMO_MEMBERS: CatalogMember[] = [
  {
    id: 'tm-1',
    name: '血煞天魔',
    title: '天魔宗宗主',
    realm: '化神后期',
    power: 260000,
    avatar: '血',
    tone: 'hp',
    group: '宗主',
    personality: '暴虐、威严',
    specialty: '魔功、杀伐',
    note: '以杀证道，魔心通天',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-2',
    name: '幽冥鬼姬',
    title: '副宗主',
    realm: '化神中期',
    power: 228000,
    avatar: '幽',
    tone: 'hp',
    group: '宗主',
    personality: '阴柔、狠辣',
    specialty: '魂道、魅惑',
    note: '笑容背后常藏杀机',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-3',
    name: '赤炼魔尊',
    title: '大长老',
    realm: '元婴后期',
    power: 145000,
    avatar: '赤',
    tone: 'mp',
    group: '长老',
    personality: '暴躁、嗜火',
    specialty: '魔丹、血炼',
    note: '丹房常年血气弥漫',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-4',
    name: '夜煞魔女',
    title: '二长老',
    realm: '元婴中期',
    power: 125000,
    avatar: '夜',
    tone: 'mp',
    group: '长老',
    personality: '妩媚、阴沉',
    specialty: '毒功、魔药',
    note: '药园尽是毒株',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-5',
    name: '骨铸魔匠',
    title: '三长老',
    realm: '元婴后期',
    power: 142000,
    avatar: '骨',
    tone: 'mp',
    group: '长老',
    personality: '阴鸷、专注',
    specialty: '炼器、骨兵',
    note: '器阁以白骨为材',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-6',
    name: '裂空魔影',
    title: '四长老',
    realm: '元婴中期',
    power: 122000,
    avatar: '裂',
    tone: 'mp',
    group: '长老',
    personality: '神秘、寡言',
    specialty: '魔阵、空间',
    note: '天魔渊阵眼由其镇守',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-7',
    name: '噬魂老魔',
    title: '五长老',
    realm: '元婴初期',
    power: 108000,
    avatar: '噬',
    tone: 'mp',
    group: '长老',
    personality: '懒散、阴狠',
    specialty: '魂修、吞噬',
    note: '表面昏聩，实则难测',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-8',
    name: '铁血魔判',
    title: '执法长老',
    realm: '元婴初期',
    power: 110000,
    avatar: '铁',
    tone: 'mp',
    group: '长老',
    personality: '冷酷无情',
    specialty: '审讯、处决',
    note: '违律者少有生还',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-9',
    name: '屠魔刀',
    title: '执法堂堂主',
    realm: '金丹后期',
    power: 85000,
    avatar: '屠',
    tone: 'hp',
    group: '执事',
    personality: '狂傲、嗜杀',
    specialty: '执法、刀术',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-10',
    name: '血簿执事',
    title: '杂务执事',
    realm: '金丹初期',
    power: 62000,
    avatar: '血',
    tone: 'jade',
    group: '执事',
    personality: '阴沉、琐碎',
    specialty: '庶务、血契账册',
    note: '经手外门杂役调配',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-11',
    name: '魔焰公子',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 63000,
    avatar: '魔',
    tone: 'gold',
    group: '亲传弟子',
    personality: '跋扈、好胜',
    specialty: '魔炎功法',
    note: '宗主亲传，锋芒毕露',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-12',
    name: '血璃',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 36000,
    avatar: '血',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷艳、聪慧',
    specialty: '血道、魅惑',
    note: '副宗主座下亲传',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-13',
    name: '狂煞',
    title: '执法弟子',
    realm: '筑基后期',
    power: 33000,
    avatar: '狂',
    tone: 'hp',
    group: '内门弟子',
    personality: '暴躁',
    specialty: '近战杀伐',
    note: '',
    attitude: '容易与玩家冲突',
    sectId: 'tianmo'
  },
  {
    id: 'tm-14',
    name: '暗影',
    title: '执法弟子',
    realm: '筑基中期',
    power: 28500,
    avatar: '暗',
    tone: 'hp',
    group: '内门弟子',
    personality: '阴沉',
    specialty: '追踪、暗杀',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-15',
    name: '石魔',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24000,
    avatar: '石',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷、寡言',
    specialty: '土系魔功',
    note: '常年镇守天魔渊深处',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-16',
    name: '小魔头',
    title: '外门弟子',
    realm: '炼气后期',
    power: 7000,
    avatar: '小',
    tone: 'jade',
    group: '外门弟子',
    personality: '嘴碎、好胜',
    specialty: '跑腿打听',
    note: '消息灵通',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-17',
    name: '毒萝',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6100,
    avatar: '毒',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴柔',
    specialty: '药园劳作',
    note: '一心想入内门',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-18',
    name: '阿煞',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5050,
    avatar: '阿',
    tone: 'jade',
    group: '杂役弟子',
    personality: '憨厚',
    specialty: '砍柴挑水',
    note: '宗门杂役数年',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-19',
    name: '小幽',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5350,
    avatar: '幽',
    tone: 'jade',
    group: '杂役弟子',
    personality: '机灵、嘴碎',
    specialty: '洒扫、传话',
    note: '常在膳堂附近转悠',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-101',
    name: '夜清尘',
    title: '魔丹阁执事',
    realm: '金丹中期',
    power: 74000,
    avatar: '夜',
    tone: 'jade',
    group: '执事',
    personality: '圆滑',
    specialty: '魔丹调配、丹房巡察',
    note: '协理大长老血炼',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-102',
    name: '赵明远',
    title: '骨器阁执事',
    realm: '金丹初期',
    power: 64000,
    avatar: '赵',
    tone: 'jade',
    group: '执事',
    personality: '懒散',
    specialty: '骨料清点、炼器后勤',
    note: '常与三长老往来',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-103',
    name: '林芙蕖',
    title: '外门执事',
    realm: '金丹初期',
    power: 61000,
    avatar: '林',
    tone: 'jade',
    group: '执事',
    personality: '认真',
    specialty: '外门考勤、血契登记',
    note: '外门弟子多惧其簿册',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-104',
    name: '周明远',
    title: '亲传弟子',
    realm: '金丹初期',
    power: 59000,
    avatar: '周',
    tone: 'gold',
    group: '亲传弟子',
    personality: '认真',
    specialty: '魔丹入门',
    note: '大长老座下亲传',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-105',
    name: '何芙蕖',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 36500,
    avatar: '何',
    tone: 'gold',
    group: '亲传弟子',
    personality: '随和',
    specialty: '毒功、魔药',
    note: '二长老座下亲传',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-106',
    name: '韩若虚',
    title: '亲传弟子',
    realm: '筑基大圆满',
    power: 34500,
    avatar: '韩',
    tone: 'gold',
    group: '亲传弟子',
    personality: '热心',
    specialty: '骨兵锤锻',
    note: '三长老座下亲传',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-107',
    name: '袁正阳',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 32500,
    avatar: '袁',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷酷',
    specialty: '魔阵推演',
    note: '四长老座下亲传',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-108',
    name: '苏剑影',
    title: '亲传弟子',
    realm: '筑基后期',
    power: 33500,
    avatar: '苏',
    tone: 'gold',
    group: '亲传弟子',
    personality: '冷艳',
    specialty: '审讯、血律',
    note: '执法长老座下亲传',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-109',
    name: '谢知微',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31620,
    avatar: '谢',
    tone: 'jade',
    group: '内门弟子',
    personality: '冷静',
    specialty: '魔功勤修',
    note: '有望冲击亲传考核',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-110',
    name: '曹有恒',
    title: '内门弟子',
    realm: '筑基后期',
    power: 30600,
    avatar: '曹',
    tone: 'jade',
    group: '内门弟子',
    personality: '狂傲',
    specialty: '血符抄写',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-111',
    name: '吕望川',
    title: '内门弟子',
    realm: '筑基中期',
    power: 27540,
    avatar: '吕',
    tone: 'jade',
    group: '内门弟子',
    personality: '嗜杀',
    specialty: '渊口巡逻',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-112',
    name: '薛鸾音',
    title: '内门弟子',
    realm: '筑基中期',
    power: 27030,
    avatar: '薛',
    tone: 'jade',
    group: '内门弟子',
    personality: '娇蛮',
    specialty: '魔典整理',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-113',
    name: '钟素心',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26520,
    avatar: '钟',
    tone: 'jade',
    group: '内门弟子',
    personality: '阴柔',
    specialty: '丹房助手',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-114',
    name: '姚听雨',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24990,
    avatar: '姚',
    tone: 'jade',
    group: '内门弟子',
    personality: '残忍',
    specialty: '器房学徒',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-115',
    name: '孔疏影',
    title: '内门弟子',
    realm: '筑基初期',
    power: 24480,
    avatar: '孔',
    tone: 'jade',
    group: '内门弟子',
    personality: '机灵',
    specialty: '阵基维护',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-116',
    name: '史怀橘',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23970,
    avatar: '史',
    tone: 'jade',
    group: '内门弟子',
    personality: '文静',
    specialty: '毒田督耕',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-117',
    name: '雷厚德',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26010,
    avatar: '雷',
    tone: 'jade',
    group: '内门弟子',
    personality: '谨慎',
    specialty: '外勤传讯',
    note: '有望冲击亲传考核',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-118',
    name: '乔悟真',
    title: '内门弟子',
    realm: '筑基后期',
    power: 31110,
    avatar: '乔',
    tone: 'jade',
    group: '内门弟子',
    personality: '嘴碎',
    specialty: '内务协理',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-119',
    name: '冷铸剑',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23460,
    avatar: '冷',
    tone: 'jade',
    group: '内门弟子',
    personality: '沉闷',
    specialty: '魔兽照看',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-120',
    name: '黄定川',
    title: '内门弟子',
    realm: '筑基中期',
    power: 25500,
    avatar: '黄',
    tone: 'jade',
    group: '内门弟子',
    personality: '圆滑',
    specialty: '试炼场值守',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-121',
    name: '高拾薪',
    title: '内门弟子',
    realm: '筑基初期',
    power: 23256,
    avatar: '高',
    tone: 'jade',
    group: '内门弟子',
    personality: '懒散',
    specialty: '山门接待',
    note: '有望冲击亲传考核',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-122',
    name: '郑斫木',
    title: '内门弟子',
    realm: '筑基中期',
    power: 26316,
    avatar: '郑',
    tone: 'jade',
    group: '内门弟子',
    personality: '好胜',
    specialty: '魔功研习',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-123',
    name: '程巡山',
    title: '内门弟子',
    realm: '筑基后期',
    power: 32130,
    avatar: '程',
    tone: 'jade',
    group: '内门弟子',
    personality: '孤僻',
    specialty: '血泉看守',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-124',
    name: '金御风',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6630,
    avatar: '金',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '药园除草',
    note: '盼着血试翻身入内门',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-125',
    name: '邱抱朴',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6752,
    avatar: '邱',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '矿洞运料',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-126',
    name: '龙崇德',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6875,
    avatar: '龙',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '山门扫地',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-127',
    name: '易浣纱',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6997,
    avatar: '易',
    tone: 'jade',
    group: '外门弟子',
    personality: '谨慎',
    specialty: '膳堂帮厨',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-128',
    name: '聂步莲',
    title: '外门弟子',
    realm: '炼气后期',
    power: 7120,
    avatar: '聂',
    tone: 'jade',
    group: '外门弟子',
    personality: '寡言',
    specialty: '洗衣浆裳',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-129',
    name: '刘无瑕',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6630,
    avatar: '刘',
    tone: 'jade',
    group: '外门弟子',
    personality: '嘴碎',
    specialty: '饲魔禽',
    note: '盼着血试翻身入内门',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-130',
    name: '孙令仪',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6752,
    avatar: '孙',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '抄录杂务',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-131',
    name: '罗慧心',
    title: '外门弟子',
    realm: '炼气后期',
    power: 6875,
    avatar: '罗',
    tone: 'jade',
    group: '外门弟子',
    personality: '清冷',
    specialty: '传信跑腿',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-132',
    name: '于琼华',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5875,
    avatar: '于',
    tone: 'jade',
    group: '外门弟子',
    personality: '妖冶',
    specialty: '灯油添换',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-133',
    name: '傅绿筠',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5957,
    avatar: '傅',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷艳',
    specialty: '柴房劈柴',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-134',
    name: '蔡黄粱',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6038,
    avatar: '蔡',
    tone: 'jade',
    group: '外门弟子',
    personality: '神秘',
    specialty: '水井汲水',
    note: '盼着血试翻身入内门',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-135',
    name: '潘金蕊',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6120,
    avatar: '潘',
    tone: 'jade',
    group: '外门弟子',
    personality: '清傲',
    specialty: '菜畦施肥',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-136',
    name: '姜禾穗',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5712,
    avatar: '姜',
    tone: 'jade',
    group: '外门弟子',
    personality: '飒爽',
    specialty: '仓储盘点',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-137',
    name: '熊药香',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5794,
    avatar: '熊',
    tone: 'jade',
    group: '外门弟子',
    personality: '温婉',
    specialty: '院落洒扫',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-138',
    name: '毛萱草',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5875,
    avatar: '毛',
    tone: 'jade',
    group: '外门弟子',
    personality: '细腻',
    specialty: '路石修补',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-139',
    name: '孟石桥',
    title: '外门弟子',
    realm: '炼气中期',
    power: 5957,
    avatar: '孟',
    tone: 'jade',
    group: '外门弟子',
    personality: '急躁',
    specialty: '试炼场擦拭',
    note: '盼着血试翻身入内门',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-140',
    name: '黎水衡',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6038,
    avatar: '黎',
    tone: 'jade',
    group: '外门弟子',
    personality: '好学',
    specialty: '魔典打杂',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-141',
    name: '文霜刃',
    title: '外门弟子',
    realm: '炼气中期',
    power: 6120,
    avatar: '文',
    tone: 'jade',
    group: '外门弟子',
    personality: '爽朗',
    specialty: '丹渣清理',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-142',
    name: '李云起',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5080,
    avatar: '李',
    tone: 'jade',
    group: '外门弟子',
    personality: '固执',
    specialty: '器屑回收',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-143',
    name: '徐月白',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5141,
    avatar: '徐',
    tone: 'jade',
    group: '外门弟子',
    personality: '耿直',
    specialty: '魔兽粪便清理',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-144',
    name: '马子昂',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4896,
    avatar: '马',
    tone: 'jade',
    group: '外门弟子',
    personality: '认真',
    specialty: '外门巡更',
    note: '盼着血试翻身入内门',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-145',
    name: '冯叔平',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4957,
    avatar: '冯',
    tone: 'jade',
    group: '外门弟子',
    personality: '随和',
    specialty: '迎客引路',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-146',
    name: '许屠魔',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5018,
    avatar: '许',
    tone: 'jade',
    group: '外门弟子',
    personality: '热心',
    specialty: '杂物搬运',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-147',
    name: '蒋断岳',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5080,
    avatar: '蒋',
    tone: 'jade',
    group: '外门弟子',
    personality: '冷酷',
    specialty: '灶火添薪',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-148',
    name: '余噬魂',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5141,
    avatar: '余',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴鸷',
    specialty: '晒药翻片',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-149',
    name: '任煞星',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4896,
    avatar: '任',
    tone: 'jade',
    group: '外门弟子',
    personality: '沉默',
    specialty: '缝补道袍',
    note: '盼着血试翻身入内门',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-150',
    name: '邹怀安',
    title: '外门弟子',
    realm: '炼气初期',
    power: 4957,
    avatar: '邹',
    tone: 'jade',
    group: '外门弟子',
    personality: '阴沉',
    specialty: '磨刀擦剑',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-151',
    name: '康致远',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5018,
    avatar: '康',
    tone: 'jade',
    group: '外门弟子',
    personality: '豪迈',
    specialty: '井绳更换',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-152',
    name: '邵景行',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5080,
    avatar: '邵',
    tone: 'jade',
    group: '外门弟子',
    personality: '勤恳',
    specialty: '篱笆修缮',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-153',
    name: '尹无咎',
    title: '外门弟子',
    realm: '炼气初期',
    power: 5141,
    avatar: '尹',
    tone: 'jade',
    group: '外门弟子',
    personality: '踏实',
    specialty: '账册誊抄',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-154',
    name: '戴掌灯',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4998,
    avatar: '戴',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '砍柴挑水',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-155',
    name: '方启扉',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5228,
    avatar: '方',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '膳堂洗碗',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-156',
    name: '陆墨池',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5458,
    avatar: '陆',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '茅厕清理',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-157',
    name: '秦药香',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5088,
    avatar: '秦',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '石阶洒扫',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-158',
    name: '万萱草',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5318,
    avatar: '万',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '柴房看守',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-159',
    name: '常蘅芷',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5548,
    avatar: '常',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '菜园浇水',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-160',
    name: '狄幽萝',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5178,
    avatar: '狄',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '喂养灵鸡',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-161',
    name: '陈霜姬',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5198,
    avatar: '陈',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清冷',
    specialty: '浆洗衣物',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-162',
    name: '胡鸾音',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5428,
    avatar: '胡',
    tone: 'jade',
    group: '杂役弟子',
    personality: '妖冶',
    specialty: '运送粪肥',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-163',
    name: '梁素心',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5058,
    avatar: '梁',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷艳',
    specialty: '擦拭门扉',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-164',
    name: '董听雨',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5288,
    avatar: '董',
    tone: 'jade',
    group: '杂役弟子',
    personality: '神秘',
    specialty: '添换灯油',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-165',
    name: '沈疏影',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5518,
    avatar: '沈',
    tone: 'jade',
    group: '杂役弟子',
    personality: '清傲',
    specialty: '清扫厢房',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-166',
    name: '贾怀橘',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5148,
    avatar: '贾',
    tone: 'jade',
    group: '杂役弟子',
    personality: '飒爽',
    specialty: '搬运砖石',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-167',
    name: '杜浣纱',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5378,
    avatar: '杜',
    tone: 'jade',
    group: '杂役弟子',
    personality: '温婉',
    specialty: '修补篱笆',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-168',
    name: '范步莲',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5398,
    avatar: '范',
    tone: 'jade',
    group: '杂役弟子',
    personality: '细腻',
    specialty: '井边打水',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-169',
    name: '金无瑕',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5028,
    avatar: '金',
    tone: 'jade',
    group: '杂役弟子',
    personality: '泼辣',
    specialty: '晒谷翻场',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-170',
    name: '邱令仪',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5258,
    avatar: '邱',
    tone: 'jade',
    group: '杂役弟子',
    personality: '聪慧',
    specialty: '灶下添薪',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-171',
    name: '龙慧心',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5488,
    avatar: '龙',
    tone: 'jade',
    group: '杂役弟子',
    personality: '内敛',
    specialty: '泔水倾倒',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-172',
    name: '易琼华',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5118,
    avatar: '易',
    tone: 'jade',
    group: '杂役弟子',
    personality: '谨慎',
    specialty: '草料堆垛',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-173',
    name: '聂绿筠',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5348,
    avatar: '聂',
    tone: 'jade',
    group: '杂役弟子',
    personality: '寡言',
    specialty: '扫落叶',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-174',
    name: '刘黄粱',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5578,
    avatar: '刘',
    tone: 'jade',
    group: '杂役弟子',
    personality: '嘴碎',
    specialty: '擦拭香案',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-175',
    name: '孙问松',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4998,
    avatar: '孙',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '山门扫地',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-176',
    name: '罗破晓',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5228,
    avatar: '罗',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '廊下抹灰',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-177',
    name: '于乘风',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5458,
    avatar: '于',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '修整竹篱',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-178',
    name: '傅栖梧',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5088,
    avatar: '傅',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '翻晒被褥',
    note: '杂役年头不短，略通人情',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-179',
    name: '蔡养浩',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5318,
    avatar: '蔡',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '淘米择菜',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-180',
    name: '潘自强',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5548,
    avatar: '潘',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '劈柴入垛',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-181',
    name: '姜通玄',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5178,
    avatar: '姜',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '清理兽栏',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-182',
    name: '熊凝锋',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5198,
    avatar: '熊',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '抬送柴捆',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-183',
    name: '毛安澜',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5428,
    avatar: '毛',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '整理工具',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-184',
    name: '孟行舟',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5058,
    avatar: '孟',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '巡夜敲梆',
    note: '杂役年头不短，略通人情',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-185',
    name: '黎担水',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5288,
    avatar: '黎',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '清晨打更',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-186',
    name: '文守夜',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5518,
    avatar: '文',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '帮厨切菜',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-187',
    name: '李司仓',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5148,
    avatar: '李',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '刷洗锅灶',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-188',
    name: '徐击柝',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5378,
    avatar: '徐',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '搬运水缸',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-189',
    name: '马录籍',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5398,
    avatar: '马',
    tone: 'jade',
    group: '杂役弟子',
    personality: '认真',
    specialty: '清扫丹渣',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-190',
    name: '冯竹简',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5028,
    avatar: '冯',
    tone: 'jade',
    group: '杂役弟子',
    personality: '随和',
    specialty: '收拾器屑',
    note: '杂役年头不短，略通人情',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-191',
    name: '许玄戈',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5258,
    avatar: '许',
    tone: 'jade',
    group: '杂役弟子',
    personality: '热心',
    specialty: '抄录杂单',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-192',
    name: '蒋铁衣',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5488,
    avatar: '蒋',
    tone: 'jade',
    group: '杂役弟子',
    personality: '冷酷',
    specialty: '传唤杂役',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-193',
    name: '余火辛',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5118,
    avatar: '余',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴鸷',
    specialty: '看守仓门',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-194',
    name: '任金锋',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5348,
    avatar: '任',
    tone: 'jade',
    group: '杂役弟子',
    personality: '沉默',
    specialty: '修补草鞋',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-195',
    name: '邹风至',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5578,
    avatar: '邹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '阴沉',
    specialty: '搓麻绳',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-196',
    name: '康星河',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 4998,
    avatar: '康',
    tone: 'jade',
    group: '杂役弟子',
    personality: '豪迈',
    specialty: '晒药翻片',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-197',
    name: '邵辰光',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5228,
    avatar: '邵',
    tone: 'jade',
    group: '杂役弟子',
    personality: '勤恳',
    specialty: '除草松土',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-198',
    name: '尹仲远',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5458,
    avatar: '尹',
    tone: 'jade',
    group: '杂役弟子',
    personality: '踏实',
    specialty: '清理水沟',
    note: '',
    attitude: '冷淡',
    sectId: 'tianmo'
  },
  {
    id: 'tm-199',
    name: '龚少游',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5088,
    avatar: '龚',
    tone: 'jade',
    group: '杂役弟子',
    personality: '急躁',
    specialty: '抬轿引路',
    note: '',
    attitude: '严格',
    sectId: 'tianmo'
  },
  {
    id: 'tm-200',
    name: '王裂空',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5318,
    avatar: '王',
    tone: 'jade',
    group: '杂役弟子',
    personality: '好学',
    specialty: '迎接访客行李',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-201',
    name: '吴焚天',
    title: '杂役弟子',
    realm: '炼气三层',
    power: 5548,
    avatar: '吴',
    tone: 'jade',
    group: '杂役弟子',
    personality: '爽朗',
    specialty: '打扫试剑场',
    note: '',
    attitude: '中立',
    sectId: 'tianmo'
  },
  {
    id: 'tm-202',
    name: '郭破军',
    title: '杂役弟子',
    realm: '炼气一层',
    power: 5178,
    avatar: '郭',
    tone: 'jade',
    group: '杂役弟子',
    personality: '固执',
    specialty: '擦拭兵器架',
    note: '杂役年头不短，略通人情',
    attitude: '友善',
    sectId: 'tianmo'
  },
  {
    id: 'tm-203',
    name: '唐清尘',
    title: '杂役弟子',
    realm: '炼气二层',
    power: 5198,
    avatar: '唐',
    tone: 'jade',
    group: '杂役弟子',
    personality: '耿直',
    specialty: '收拾膳堂残羹',
    note: '',
    attitude: '友善',
    sectId: 'tianmo'
  }
]

/** 已知女性姓名（供默认头像推断） */
export const TIANMO_FEMALE_NAMES = [
  "幽冥鬼姬",
  "夜煞魔女",
  "血璃",
  "毒萝",
  "小幽",
  "林芙蕖",
  "何芙蕖",
  "苏剑影",
  "薛鸾音",
  "钟素心",
  "姚听雨",
  "孔疏影",
  "史怀橘",
  "易浣纱",
  "聂步莲",
  "刘无瑕",
  "孙令仪",
  "罗慧心",
  "于琼华",
  "傅绿筠",
  "蔡黄粱",
  "潘金蕊",
  "姜禾穗",
  "熊药香",
  "毛萱草",
  "秦药香",
  "万萱草",
  "常蘅芷",
  "狄幽萝",
  "陈霜姬",
  "胡鸾音",
  "梁素心",
  "董听雨",
  "沈疏影",
  "贾怀橘",
  "杜浣纱",
  "范步莲",
  "金无瑕",
  "邱令仪",
  "龙慧心",
  "易琼华",
  "聂绿筠",
  "刘黄粱"
] as const
