/** 矿石图标：由 scripts/slice-ore-icons.mjs 自图鉴切片生成 */

export const ORE_ICON_DIR = '/assets/ores/icons'

/** 图鉴切片名 → 文件名 */
export const ORE_ICON_FILES: Record<string, string> = {
  '青云铁': 'ore-001.png',
  '青灵石': 'ore-002.png',
  '寒铁矿': 'ore-003.png',
  '聚灵石': 'ore-004.png',
  '温玉矿': 'ore-005.png',
  '灵晶砂': 'ore-006.png',
  '青木灵石': 'ore-007.png',
  '镇魂石': 'ore-008.png',
  '玄钢矿': 'ore-009.png',
  '幽冥砂': 'ore-010.png',
  '月影石': 'ore-011.png',
  '寒魄石': 'ore-012.png',
  '紫云铁': 'ore-013.png',
  '天青石': 'ore-014.png',
  '星纹铁': 'ore-015.png',
  '紫灵晶': 'ore-016.png',
  '九转灵晶': 'ore-017.png',
  '聚灵玉': 'ore-018.png',
  '青木晶': 'ore-019.png',
  '灵髓石': 'ore-020.png',
  '月华石': 'ore-021.png',
  '山岳玄铁': 'ore-022.png',
  '厚土晶高阶': 'ore-023.png',
  '镇山石': 'ore-024.png',
  '赤金矿': 'ore-025.png',
  '炎阳晶': 'ore-026.png',
  '火云石': 'ore-027.png',
  '金乌灵晶': 'ore-028.png',
  '熔岩精金': 'ore-029.png',
  '太阴石': 'ore-030.png',
  '玄冰晶': 'ore-031.png',
  '月魄玉': 'ore-032.png',
  '幽月银': 'ore-033.png',
  '寒星石': 'ore-034.png',
  '金灵晶': 'ore-035.png',
  '玄水晶': 'ore-036.png',
  '赤炎晶': 'ore-037.png',
  '厚土晶': 'ore-038.png',
  '五行灵玉': 'ore-039.png',
  '通天玄铁': 'ore-040.png',
  '星陨铁': 'ore-041.png',
  '天青神石': 'ore-042.png',
  '剑魂晶': 'ore-043.png',
  '庚金精魄': 'ore-044.png',
  '紫霄铁': 'ore-045.png',
  '九龙炎晶': 'ore-046.png',
  '赤炎神铁': 'ore-047.png',
  '火龙玉': 'ore-048.png',
  '斩仙神铁': 'ore-049.png',
  '庚金神晶': 'ore-050.png',
  '太白精金': 'ore-051.png',
  '天外陨铁': 'ore-052.png',
  '杀伐晶': 'ore-053.png',
  '仙纹铁': 'ore-054.png',
  '太虚石': 'ore-055.png',
  '虚空晶': 'ore-056.png',
  '星辰铁': 'ore-057.png',
  '空冥石': 'ore-058.png',
  '天河神砂': 'ore-059.png',
  '空间灵髓': 'ore-060.png',
  '星界晶': 'ore-061.png',
  '万魂石': 'ore-062.png',
  '幽冥铁': 'ore-063.png',
  '魂晶': 'ore-064.png',
  '阴煞石': 'ore-065.png',
  '九幽玄晶': 'ore-066.png',
  '冥河砂': 'ore-067.png',
  '空冥玉': 'ore-068.png',
  '空间神石': 'ore-069.png',
  '镜魂晶': 'ore-070.png',
  '太虚银': 'ore-071.png',
  '界石': 'ore-072.png',
  '时光石': 'ore-073.png',
  '岁月晶': 'ore-074.png',
  '星河砂': 'ore-075.png',
  '时间神砂': 'ore-076.png',
  '轮回玉': 'ore-077.png',
  '因果石': 'ore-078.png',
  '天命晶': 'ore-079.png',
  '玄天玉': 'ore-080.png',
  '道纹金': 'ore-081.png',
  '命运神砂': 'ore-082.png',
  '因果神铁': 'ore-083.png',
  '太阳精金': 'ore-084.png',
  '阴阳玉': 'ore-085.png',
  '乾坤石': 'ore-086.png',
  '两仪晶': 'ore-087.png',
  '道韵金': 'ore-088.png',
  '混沌石': 'ore-089.png',
  '混沌神晶': 'ore-090.png',
  '鸿蒙玄铁': 'ore-091.png',
  '太初金': 'ore-092.png',
  '虚无石': 'ore-093.png',
  '道源晶': 'ore-094.png',
  '混元神金': 'ore-095.png',
  '诛仙神铁': 'ore-096.png',
  '山河神石': 'ore-097.png',
  '乾坤玉': 'ore-098.png',
  '世界晶': 'ore-099.png',
  '地脉神髓': 'ore-100.png',
  '五行神石': 'ore-101.png',
  '空间道晶': 'ore-102.png',
  '六道石': 'ore-103.png',
  '轮回神晶': 'ore-104.png',
  '幽冥神晶': 'ore-105.png',
  '黄泉石': 'ore-106.png',
  '生死玄金': 'ore-107.png',
  '轮回神砂': 'ore-108.png',
  '魂道晶': 'ore-109.png',
  '天机石': 'ore-110.png',
  '星命晶': 'ore-111.png',
  '紫微神玉': 'ore-112.png',
  '因果玄金': 'ore-113.png',
  '天演石': 'ore-114.png',
  '命运晶': 'ore-115.png',
  '九天雷晶': 'ore-116.png',
  '紫霄神铁': 'ore-117.png',
  '雷劫石': 'ore-118.png',
  '天雷精金': 'ore-119.png',
  '雷神晶': 'ore-120.png',
  '紫电玉': 'ore-121.png',
  '追命神铁': 'ore-122.png',
  '天命石': 'ore-123.png',
  '因果晶': 'ore-124.png',
  '杀伐神金': 'ore-125.png',
  '命运遗石': 'ore-126.png',
  '天劫石': 'ore-127.png',
  '雷霆神晶': 'ore-128.png',
  '九天玄铁': 'ore-129.png',
  '紫霄玉': 'ore-130.png',
  '避劫神金': 'ore-131.png',
  '天雷石': 'ore-132.png',
  '鸿蒙神石': 'ore-133.png',
  '太初神金': 'ore-134.png',
  '虚无道石': 'ore-135.png',
  '鸿蒙紫玉': 'ore-136.png',
  '世界本源晶': 'ore-137.png',
  '天道石': 'ore-138.png',
  '天机神晶': 'ore-139.png',
  '因果道金': 'ore-140.png',
  '命运神玉': 'ore-141.png',
  '法则晶': 'ore-142.png',
  '星辰道石': 'ore-143.png',
  '天道本源': 'ore-144.png',
}

/** 目录名与图鉴名差异 */
export const ORE_ICON_ALIASES: Record<string, string> = {
  玄铜矿: '玄钢矿',
  镇魂晶: '镜魂晶',
  遁源晶: '道源晶',
  避纹金: '道纹金',
  避韵金: '道韵金',
  /** 图鉴高阶行同位近似图 */
  玄黄玉: '厚土晶高阶',
  地脉石: '镇山石',
  青铜灵矿: '山岳玄铁',
  熔天石: '火龙玉',
  朱雀晶: '九龙炎晶',
  玄冥寒晶: '玄冰晶',
  万年玄冰: '寒星石',
  幽水玉: '月魄玉',
  寒魄精金: '寒魄石',
  北冥石: '太阴石',
  戮仙玄金: '诛仙神铁',
  陷仙寒晶: '玄冰晶',
  绝仙石: '诛仙神铁',
  杀戮晶: '杀伐晶',
  剑魂神玉: '剑魂晶',
  阵纹石: '道纹金'
}

export const ORE_LEVEL_ICON_FALLBACK: Record<string, string> = {
  '灵矿': '青云铁',
  '高阶灵矿': '紫云铁',
  '神矿': '赤金矿',
  '仙矿': '斩仙神铁',
  '道矿': '时光石',
  '镇界神材': '山河神石',
  '天材': '九天雷晶',
  '先天神材': '鸿蒙神石',
  '先天道材': '鸿蒙神石',
  '本源': '天道本源',
}

export function resolveOreIconName(name: string, level?: string): string | null {
  if (ORE_ICON_FILES[name]) return name
  const alias = ORE_ICON_ALIASES[name]
  if (alias && ORE_ICON_FILES[alias]) return alias
  if (level) {
    const fb = ORE_LEVEL_ICON_FALLBACK[level]
    if (fb && ORE_ICON_FILES[fb]) return fb
  }
  return null
}

/** 返回可用于 <image src> 的路径；无图时返回空串 */
export function getOreIconSrc(name: string, level?: string): string {
  const key = resolveOreIconName(name, level)
  if (!key) return ''
  const file = ORE_ICON_FILES[key]
  // Vite / Taro：用相对 assets 的 import 映射更稳，见 OreIcon 组件
  return `${ORE_ICON_DIR}/${file}`
}
